name: 'Bash Script'

on:
# now add the workflow_on event: this means that this will only be ran when called  from another workflow
  # push:
  #   branches:
  #     - main
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test Linux server
        run: |
          touch index.txt
          echo "Hello world" >> index.txt
          cat index.txt
          echo "$GITHUB_TOKEN"
          ls
      - name: Custom bash script
        run: |
          node --version
          npm run script
          ls
          chmod +x test.sh
          bash test.sh
